language: python
install:
  - pip install tox
dist: xenial
python: 3.6  # Use the oldest supported version of python as default.
script:
    - tox -e $TOX_ENV
matrix:
  include:
    - env: TOX_ENV=lint
    - python: 3.7
      env: TOX_ENV=py37
    - env: TOX_ENV=py36
      install:
        - pip install codecov
        - pip install tox
      after_success:
        # Correct coverage xml for coverage services.
        - >
          bash -c 'set -eux;
          pkg_path=$(find .tox/py*/lib/python*/site-packages/biowdl_input_converter -maxdepth 0 -type d);
          sed -i "s:${pkg_path}:src/pytest_workflow:g" coverage.xml'
        - codecov -v  # -v to make sure coverage upload works.

